# Default values for bookkeeper
replicaCount: 3

image:
  repository: apache/bookkeeper
  pullPolicy: IfNotPresent
  tag: "4.16.1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# ZooKeeper configuration
zookeeper:
  # ZooKeeper metadata service URI (required)
  metadataServiceUri: "zk://zookeeper:2181/ledgers"

# BookKeeper configuration
bookkeeper:
  # Journal and ledger directories
  journalDirectory: "/opt/bookkeeper/data/journal"
  ledgerDirectories: "/opt/bookkeeper/data/ledgers"
  indexDirectories: "/opt/bookkeeper/data/index"
  
  # Metadata formatting
  metaformat:
    # Enable automatic metadata formatting on first deployment
    enabled: true
    # Force format even if metadata exists (dangerous - only for development)
    force: false
  
  # BookKeeper specific settings
  config:
    # Bookie port
    bookiePort: 3181
    # HTTP server port
    httpServerPort: 8080
    # Number of journal files to pre-allocate
    journalPreAllocSizeMB: 16
    # Enable statistics
    enableStatistics: true
    # Garbage collection settings
    gcWaitTime: 900000
    # Entry log size limit
    entryLogSizeLimit: 536870912

# Service configuration
service:
  type: ClusterIP
  port: 3181
  httpPort: 8080

# Headless service for StatefulSet
headlessService:
  enabled: true

# Persistent storage
persistence:
  enabled: true
  storageClass: ""
  size: 10Gi
  accessMode: ReadWriteOnce

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Node selection
nodeSelector: {}
tolerations: []
affinity: {}

# Security context
securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  runAsNonRoot: true

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /heartbeat
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /api/v1/bookie/state
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3

# ServiceMonitor for Prometheus (optional)
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
