apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bookkeeper.fullname" . }}-config
  labels:
    {{- include "bookkeeper.labels" . | nindent 4 }}
data:
  bk_server.conf: |
    # BookKeeper server configuration
    bookiePort={{ .Values.bookkeeper.config.bookiePort }}
    httpServerPort={{ .Values.bookkeeper.config.httpServerPort }}
    
    # ZooKeeper settings
    zkServers={{ .Values.zookeeper.metadataServiceUri }}
    metadataServiceUri={{ .Values.zookeeper.metadataServiceUri }}
    
    # Storage settings
    journalDirectory={{ .Values.bookkeeper.journalDirectory }}
    ledgerDirectories={{ .Values.bookkeeper.ledgerDirectories }}
    indexDirectories={{ .Values.bookkeeper.indexDirectories }}
    
    # Performance settings
    journalPreAllocSizeMB={{ .Values.bookkeeper.config.journalPreAllocSizeMB }}
    entryLogSizeLimit={{ .Values.bookkeeper.config.entryLogSizeLimit }}
    gcWaitTime={{ .Values.bookkeeper.config.gcWaitTime }}
    
    # Statistics
    enableStatistics={{ .Values.bookkeeper.config.enableStatistics }}
    
    # Enable auto recovery
    autoRecoveryDaemonEnabled=true
    
    # Disk usage threshold
    diskUsageThreshold=0.95
    diskUsageWarnThreshold=0.90
