replicaCount: 3
zookeeper:
  servers:
    - tp-zookeeper:2181
  metadataServiceUri: "zk://tp-zookeeper:2181/bookkeeper"
persistence:
  size: 20Gi
  storageClass: "nfs-client"
resources:
  requests:
    memory: 2Gi
    cpu: 1000m
  limits:
    memory: 4Gi
    cpu: 2000m
bookkeeper:
  metaformat:
    enabled: false
    force: true
securityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0
podSecurityContext:
  runAsNonRoot: false
